# Generated by Django 2.2.16 on 2022-11-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221126_1041'),
        ('users', '0003_auto_20221126_0123'),
    ]

    operations = [
    ]
